---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

#  wallet-service:
#    build: ./wallet-service
#    container_name: wallet-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - mongodb
#    networks:
#      - spring
#      - mongo-wallet
#
#  mongodb:
#    image: mongo
#    container_name: mongodb
#    networks:
#      - mongo-wallet
#
#  transaction-service:
#    build: ./transaction-service
#    container_name: transaction-service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - transactiondb
#    networks:
#      - spring
#      - postgres-transaction
#
#  transactiondb:
#    image: postgres:12-alpine
#    environment:
#      - POSTGRES_DB=transaction_service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    networks:
#      - postgres-transaction
#
#  discovery-server:
#    build: ./discovery-server
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    depends_on:
#      - transaction-service
#      - wallet-service
#    networks:
#      - spring
#
#  api-gateway:
#    build: ./api-gateway
#    container_name: api-gateway
#    ports:
#      - "8080:8080"
#    depends_on:
#      - gatewaydb
#      - discovery-server
#    networks:
#      - spring
#      - postgres-gateway
#
#  gatewaydb:
#    image: postgres:12-alpine
#    environment:
#      - POSTGRES_DB=gateway_service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    networks:
#      - postgres-gateway
#
#networks:
#  spring:
#    driver: bridge
#  mongo-wallet:
#    driver: bridge
#  postgres-transaction:
#    driver: bridge
#  postgres-gateway:
#    driver: bridge
